### ISSUE TITLE
Can you show a sample of that using IBOutlets?

### ISSUE THREAD

**Issue by RafaelPlantard** [iaaqib/ContainerView#1]
Please, I try use your approach with outlets and didn't works.

**Comment by iaaqibhussain** [comment]
@RafaelPlantard You mean you created @IBOutlets of the Buttons on the main screen?

**Comment by RafaelPlantard** [comment]
I mean @IBOutlets at first and second view controllers.

**Comment by iaaqibhussain** [comment]
I am closing this issue. As it was some error from your end.
