### ISSUE TITLE
How to pass data from mainVC to the containerView you selected?

### ISSUE THREAD

**Issue by FredvanRijswijk** [iaaqib/ContainerView#2]
Normal you pass some data with prepare segue to your view, so you can preform a query or pass that data into a tableview... Now I'm stuck because the segment is passing the button to show the right containerview, but is nog aware off some var I want to pass to the destination view

**Comment by iaaqibhussain** [comment]
Hi @FredvanRijswijk !
I have updated my code now you can pass data from your Main View Controller to Container view.
 
let's say you have container view named FirstViewController.
<pre>
if let getFirstVCObject = self.container.currentViewController as? FirstViewController
        {

         //pass your data with your getFirstVCObject
        
        }
</pre>
Kindly check out the updated code.

Apologies for the late response.
Thanks. :)
